package com.example.viewer_2020.constants

class MatchDetailsConstants {

    enum class USERS(val dataPoints: List<String>) {
        NONE(
            listOf(
                "auto_avg_balls_high",
                "auto_avg_balls_low",
                "avg_incap_time",
                "team_number",
                "tele_avg_balls_high",
                "tele_avg_balls_low",
                "auto_max_balls_low",
                "auto_max_balls_high",
                "tele_max_balls_low",
                "tele_max_balls_high",
                "driver_ability",
                "drivetrain",
                "auto_line_successes",
                "mode_start_position",
                "climb_percent_success",
                "low_rung_successes",
                "mid_rung_successes",
                "high_rung_successes",
                "traversal_rung_successes",
                "climb_all_attempts"
            )
        ),
        AUSTIN(
            listOf(
                "auto_avg_balls_high",
                "auto_avg_balls_low",
                "avg_incap_time",
                "team_number",
                "tele_avg_balls_high",
                "tele_avg_balls_low",
                "auto_max_balls_low",
                "auto_max_balls_high",
                "tele_max_balls_low",
                "tele_max_balls_high",
                "driver_ability",
                "drivetrain",
                "auto_line_successes",
                "mode_start_position",
                "climb_percent_success",
                "low_rung_successes",
                "mid_rung_successes",
                "high_rung_successes",
                "traversal_rung_successes",
                "climb_all_attempts"
            )
        ),
        DAVE(
            listOf(
                "auto_avg_balls_high",
                "auto_avg_balls_low",
                "avg_incap_time",
                "team_number",
                "tele_avg_balls_high",
                "tele_avg_balls_low",
                "auto_max_balls_low",
                "auto_max_balls_high",
                "tele_max_balls_low",
                "tele_max_balls_high",
                "driver_ability",
                "drivetrain",
                "auto_line_successes",
                "mode_start_position",
                "climb_percent_success",
                "low_rung_successes",
                "mid_rung_successes",
                "high_rung_successes",
                "traversal_rung_successes",
                "climb_all_attempts"
            )
        ),
        KATE(
            listOf(
                "auto_avg_balls_high",
                "auto_avg_balls_low",
                "avg_incap_time",
                "team_number",
                "tele_avg_balls_high",
                "tele_avg_balls_low",
                "auto_max_balls_low",
                "auto_max_balls_high",
                "tele_max_balls_low",
                "tele_max_balls_high",
                "driver_ability",
                "drivetrain",
                "auto_line_successes",
                "mode_start_position",
                "climb_percent_success",
                "low_rung_successes",
                "mid_rung_successes",
                "high_rung_successes",
                "traversal_rung_successes",
                "climb_all_attempts"
            )
        ),
        MIKE(
            listOf(
                "auto_avg_balls_high",
                "auto_avg_balls_low",
                "avg_incap_time",
                "team_number",
                "tele_avg_balls_high",
                "tele_avg_balls_low",
                "auto_max_balls_low",
                "auto_max_balls_high",
                "tele_max_balls_low",
                "tele_max_balls_high",
                "driver_ability",
                "auto_line_successes",
                "climb_percent_success",
                "low_rung_successes",
                "mid_rung_successes",
                "high_rung_successes",
                "traversal_rung_successes"
            )
        ),
        RICHARD(
            listOf(
                "auto_avg_balls_high",
                "auto_avg_balls_low",
                "avg_incap_time",
                "team_number",
                "tele_avg_balls_high",
                "tele_avg_balls_low",
                "auto_max_balls_low",
                "auto_max_balls_high",
                "tele_max_balls_low",
                "tele_max_balls_high",
                "current_rank",
                "predicted_score",
                "driver_ability",
                "auto_line_successes",
                "driver_near_field_awareness",
                "driver_far_field_awareness",
                "mode_start_position",
                "climb_percent_success",
                "low_rung_successes",
                "mid_rung_successes",
                "high_rung_successes",
                "traversal_rung_successes",
                "avg_exit_ball_catches",
                "avg_opp_balls_scored"
            )
        )
    }
}

